analyzer:
  strong-mode: true
  errors:
    # Allow importing .template.dart files without an analyzer error.
    uri_has_not_been_generated: ignore
  exclude:
    - "**/.dart_tool/**"
    - "**/build/**"
# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
