name: my_angular_project
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: xavier <email@example.com>

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+11
  angular_components:
  angular_router:
  angular_forms:

dev_dependencies:
  build_runner:
  build_web_compilers: