name: server
version: 0.0.1
#homepage: https://www.example.com
#author: xavier <email@example.com>

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  shelf:
  shelf_static:
  shelf_route:
  shelf_proxy:
